version: '2'
services:
  twentyonepoints-app:
    image: twentyonepoints
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://twentyonepoints-mysql:3306/twentyonepoints?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://twentyonepoints-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://twentyonepoints-elasticsearch:9200
    ports:
      - 8080:8080
  twentyonepoints-mysql:
    extends:
      file: mysql.yml
      service: twentyonepoints-mysql
  twentyonepoints-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: twentyonepoints-elasticsearch
